defaultPortal: kaksio_task
portals:
  - name: kaksio_task
    portalId: 21525269
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNa0gvj2LxIJAA0AAAAA4A0DGJXmoQogi9_wFCju6QwyFBgOnA4IydAuMHdyJHtdbXolniq-OigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhQtlk9VDE7itLW7CsARzuiaxVSLXkoDbmExUgBaAA
        expiresAt: '2022-03-09T14:06:24.857Z'
    personalAccessKey: >-
      CiRkOGJlNDUyYS0wOTM4LTQ2MmItYjU4ZC1lZWMxYzdhYWRmMTgQleahChiL3_AUKhkABeaRgtzLAjyKkAvJqCm29MHG_FMbTOKCSgNuYTE
